- name: Download fisher.config
  get_url:
    url: https://git.io/fisher
    dest: /tmp/fisher.config

- name: Install
  shell:
    cmd: "source /tmp/fisher.config && fisher install jorgebucaran/fisher"
    executable: /usr/bin/fish