- name: Download
  unarchive:
    src: "{{ exa_url }}"
    dest: /tmp/exa
    remote_src: yes

- name: Install bin 
  become: yes
  shell: mv /tmp/exa/bin/exa /usr/local/bin
  args:
    chdir: /tmp

- name: Install doc
  become: yes
  shell: mv /tmp/exa/man/* /usr/share/man/man1
  args:
    chdir: /tmp

- name: Install completion
  become: yes
  shell: mv /tmp/exa/completions/exa.fish /usr/share/fish/vendor_completions.d
  args:
    chdir: /tmp
