- import_role: { name: check/absent }
  vars:
    target: jethrokuan_z
    command: "/usr/bin/fish -c 'fisher list | grep -E jethrokuan/z'"

- import_tasks: install.yml
  when: jethrokuan_z_is_absent
